### ISSUE TITLE
Teacher needs the server to support "retake"

### ISSUE THREAD

**Issue by chrqls** [RazortoothRTC/node-smile-server#42]
Relative issue: https://github.com/SMILEConsortium/node-smile-server/issues/15

**Comment by chrqls** [comment]
![screen shot 2014-02-15 at 03 16 10](https://f.cloud.github.com/assets/3521208/2177695/a3e0cbd4-9632-11e3-9623-b0e835e3c0e8.png)

**Comment by chrqls** [comment]
![screen shot 2014-02-15 at 03 16 46](https://f.cloud.github.com/assets/3521208/2177699/be6a6d20-9632-11e3-9739-34697edd10a5.png)

**Comment by chrqls** [comment]
![screen shot 2014-02-15 at 03 17 25](https://f.cloud.github.com/assets/3521208/2177700/d00bddd4-9632-11e3-9386-81ca2b5171a8.png)

**Comment by chrqls** [comment]
![screen shot 2014-02-15 at 03 17 58](https://f.cloud.github.com/assets/3521208/2177701/e3070562-9632-11e3-9a03-780d07af6222.png)

**Comment by truedat101** [comment]
There's probably bugs in the "retake" because this was never completely implemented. The code partially exists on both sides. As you can see @thiago didn't completely finish this feature. I would like it if you can focus on this, how to implement per the JAMsj requirement:

```
Teacher runs a session with prepared question set A
Teacher completes session, would like to run prepared question Set B.
Teacher hits "Send New IQSet" button
This should restart the teacher tablet, with the selection of prepared questions
Once selected an iqset, students are reset to "Start Answer Questions Phase" without being logged out, and all existing scores are reset.
```

Related to https://github.com/RazortoothRTC/smile_teacher_android/issues/23#issuecomment-36648067

**Comment by chrqls** [comment]
@truedat101 , the last changes fix a lot of stuff in this issue and I found a way to redirect students when the teacher retakes. But when the teacher start solving questions, the student gets directly the message:

```
Done. Please wait for the rest of the students to finish Answering Questions
```

...without having the possibility to **first** answer to the questions. 
However, the variables in **smilestudent.js** seems updated as you can see:
![screen shot 2014-04-01 at 23 49 54](https://cloud.githubusercontent.com/assets/3521208/2585118/cb9c8086-b9e7-11e3-9866-c91fcb7c63e0.png)
Here is the condition which start this popup:

``` javascript
if ((GlobalViewModel.qidx() + 1) < GlobalViewModel.numq()) {
        // code...
    } else {
        // Submit All Questions
        $('div#answer-form-area').block({
            message: '<h1>Done.  Please wait for the rest of the students to finish Answering Questions</h1>',
            css: { border: '3px solid #a00', width: '80%'
            }
        });
       // code...
    }
```

but the variables does not match with the result:
![screen shot 2014-04-01 at 23 50 26](https://cloud.githubusercontent.com/assets/3521208/2585157/8b33b37e-b9e8-11e3-81f1-936c612383a7.png)
![screen shot 2014-04-01 at 23 50 43](https://cloud.githubusercontent.com/assets/3521208/2585160/8ed85642-b9e8-11e3-91de-ca23e2c42450.png)

I am still looking for a way to understand why.

**Comment by truedat101** [comment]
Not working.  See debug out below:

```

Retaking...
Adding question...
WARNING: Ignoring duplicated question: The Army assumed an internee who answered No and No to questions #27 and #28 meant that he was ______________________the United States. (teacher-876ec7c0e5b2d1bbfb021e31d9bc3859d5dd20be).
Adding question...
WARNING: Ignoring duplicated question: Why did Issei men respond No to question #27 or #28? (teacher-867e01d4fa9a1127dcb25b342073835b29bda2b3).
Adding question...
WARNING: Ignoring duplicated question: Why did Nisei men respond Yes to question #27  or #28? (teacher-8c60be98dd0aeec8e313a591c5e2ab35fdd78bb3).
Adding question...
WARNING: Ignoring duplicated question: How many men were convicted of draft resistance in the camps? (teacher-f771605376c6cbba575034c6d8a34dc99b74fb9c).
Adding question...
WARNING: Ignoring duplicated question: Which camp had the highest number of draft resisters? (teacher-598fe9ee199b371ed4dadf5266eb06ec1750e6e2).
Adding question...
WARNING: Ignoring duplicated question: Which of the following was NOT a Supreme Court case challenging the constitutionality of the  World War II experience for Japanese Americans? (teacher-6a927abd3ce8c6dc9452bdb7cfef7fb172a7c17c).

```

**Comment by truedat101** [comment]
It would appear that after reloading a question, you have not properly dumped the current questions.  Perhaps the feature works fine if you select a different set of questions for retake.  Please fix this case as well.  Verify the number of questions sent.

**Comment by chrqls** [comment]
This change allows the teacher to retake several times on the same IQSet and it also fix the problem of "empty questions".

**Comment by truedat101** [comment]
Verified.
